label: cbf
x_dim: 3
y_dim: 2
n_sample: 300
n_validation: 1
n_evaluation: 1
lr: 0.0001
lr_scheduler: none
lr_scheduler_milestones: [2000, 5000, 8000]
projection_on: 0
lr_scheduler_gamma: 0.3
n_epochs: 1000
batch_size: 300
training_seed: 1
hiddenSize: 200
softWeight: 100
probType: cbf
log_freq: 10
save_freq: 1000
resume: false
resume_from:
dt: 0.1
T_train: 15
T_eval: 10
plot:
  trajectory:
    figsize: [6, 6]
    dpi: 300
    label_fontsize: 10
    tick_fontsize: 10
    obstacle_label_fontsize: 10
  control:
    figsize: [6, 6]
    dpi: 300
    label_fontsize: 10
    tick_fontsize: 10
    y_tick_format: "%.1f"
  loss:
    figsize: [6, 10]
    dpi: 300
    label_fontsize: 10
    tick_fontsize: 10
    title_fontsize: 10
    legend_fontsize: 10
    epoch_start:
    epoch_end:
    last_n_epochs:
kappa: 10
alpha: 1
cbf_violation: 0.0
Q: [1000, 1000, 1]
R: [1, 1]
Qf: [1000000, 1000000, 1]
x_0: [[-4.5], [0], [0.5]]
controller:
  k_p:
    - 0.01
    - 0.2
    - -0.0
  k_i:
    - 0.05
    - 0.005
    - -0.0
  k_d:
    - 0.0
    - 0.01
    - -0.0
obs:
  - label: O1
    vertices:
      - [-0.36282, -0.08718]
      - [-0.06282, -0.38718]
      - [0.08718, 0.36282]
      - [-0.51282, 0.21282]
      - [0.53718, -0.08718]
    center: [-1.2, 0.0]
  - label: O2
    vertices:
      - [-0.3, 0.12]
      - [0.21969, 0.33123]
      - [-0.23031, 0.39123]
      - [-0.15, -0.3]
      - [-0.08031, 0.45123]
      - [0.51969, -0.50877]
    center: [-1.5, -2.0]
  - label: O3
    vertices:
      - [0, -0.6]
      - [0.1671, -0.6]
      - [-0.28329, -0.1]
      - [0.31671, 0.0]
      - [0.01671, 0.6]
    center: [-2.8, 0.5]
constraints:
  x:
    lb: [-5, -4, -3.14]
    ub: [1, 2, 3.14]
  u:
    lb: [-0.01, -0.5]
    ub: [1, 0.5]
  x_sample:
    lb: [-5, -4, -3.14]
    ub: [1, 2, 3.14]
net:
  # num_hidden: 2
  # hidden: 200
  # hidden_tf: 80
  num_hidden: 3
  hidden: 200
  hidden_tf: 120
  # num_hidden: 16
  # hidden: 256
  # hidden_tf: 384
